### ISSUE TITLE
Implement Item List in Wardrobe Page

### ISSUE THREAD

**Issue by leodenault** [leodenault/fashion#3]
Display items in section 5 of the wardrobe.
### Tasks
- [ ] ~~Create a primitive class for representing clothing items~~
- [x] Create a loading mechanism from JSON to populate the types of clothing
- [x] Layout the UI to display clothing items
